# Main doc: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/introduction-to-github-actions
# Runners spec: https://docs.github.com/en/free-pro-team@latest/actions/reference/specifications-for-github-hosted-runners
# Glob expressions: https://github.com/actions/toolkit/tree/main/packages/glob

name: Windows

###############################################################################
# Schedule:
# - push on any branch whose name matches v** or master
# - any pull request
###############################################################################
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
    inputs:
      platform:
        description: 'Arguments for the platform script:'
        required: true
        default: '-extent=x -parallel=p -jobs=2 -large=e -compcert=y -set-switch=y'

###############################################################################
# Platform script options shared among all jobs
###############################################################################
env:
  PLATFORM_ARGS: -extent=x -parallel=p -jobs=2 -large=e -compcert=y -set-switch=y
  COQREGTESTING: y

###############################################################################
# Windows
#
# 2 jobs, the former builds the installer, the second tests it
#
# CAVEATS:
# - git is misconfigured, by default it puts \r in between \n\n
###############################################################################
jobs:
  Windows_platform:
    name: Windows
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        architecture:
          - '64'
        variant:
          # Keep this in sync with the Smoke test below
          - '9.0+preview~2025.08'
          - '8.20~2025.01'

    steps:
      - name: Set git to use LF
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf

      - name: Git checkout
        uses: actions/checkout@v4

      - name: Set PLATFORM
        if: ${{ github.event.inputs.platform != '' }}
        run: echo "PLATFORM=${{ github.event.inputs.platform }}" >> $GITHUB_ENV

      - name: Clean previous cygwin root
        shell: cmd
        run: if exist C:\cygwin_coq_platform rmdir /S /Q C:\cygwin_coq_platform

      - name: Run common platform script
        shell: cmd
        continue-on-error: ${{ !startsWith(matrix.variant, '8.') }}
        run: coq_platform_make_windows.bat -destcyg=C:\cygwin_coq_platform -arch=${{matrix.architecture}} -packages=${{matrix.variant}} %PLATFORM_ARGS% -dumplogs

      - name: Install coqdep sanitizer (after cygwin is installed)
        if: ${{ !startsWith(matrix.variant, '8.') }}
        shell: pwsh
        run: |
          $cmd = @'
          set -eu
          (set -o pipefail) 2>/dev/null || true
          mkdir -p /usr/local/bin
          cat >/usr/local/bin/coqdep <<'SH'
          #!/usr/bin/env bash
          set -eu
          (set -o pipefail) 2>/dev/null || true
          # Normalise "C\:/.../rocqworker.exe" -> "/cygdrive/c/.../rocqworker.exe"
          filter='s#[[:space:]]([A-Za-z])\\:/([^ ]*rocqworker\.exe)#[ /cygdrive/\L\1/\2]#g'
          if command -v coqdep.exe >/dev/null 2>&1; then
            exec "$(command -v coqdep.exe)" "$@" | sed -E "$filter"
          elif command -v rocq >/dev/null 2>&1; then
            exec rocq dep "$@" | sed -E "$filter"
          else
            echo "coqdep-sanitize: neither coqdep.exe nor rocq found" >&2
            exit 127
          fi
          SH
          chmod +x /usr/local/bin/coqdep
          '@
          # IMPORTANT: convertir CRLF -> LF avant de passer à bash
          $cmdLF = $cmd -replace "`r`n","`n" -replace "`r",""
          & "C:\cygwin_coq_platform\bin\bash" --login -lc $cmdLF

      - name: Rebuild affected libs after sanitizer (>=9 only)
        if: ${{ !startsWith(matrix.variant, '8.') }}
        shell: pwsh
        run: |
          $cmd = @'
          set -eu
          (set -o pipefail) 2>/dev/null || true

          if ! command -v opam >/dev/null 2>&1; then
            echo "opam not found in PATH — skipping rebuild."
            exit 0
          fi

          [ -d /opam ] && export OPAMROOT=/opam

          if ! opam switch show >/dev/null 2>&1; then
            sw="$(opam switch list --short | head -n1 || true)"
            if [ -z "$sw" ]; then
              echo "No opam switch found — skipping rebuild."
              exit 0
            fi
            eval "$(opam env --switch="$sw")"
          else
            eval "$(opam env)"
          fi

          echo "Using switch: $(opam switch show)"

          opam reinstall -y coq-flocq coq-coquelicot || opam install -y coq-flocq coq-coquelicot
          '@
          $cmdLF = $cmd -replace "`r`n","`n" -replace "`r",""
          & "C:\cygwin_coq_platform\bin\bash" --login -lc $cmdLF

      - name: Create installer
        shell: cmd
        run: C:\cygwin_coq_platform\bin\bash --login -c "cd /platform/ && windows/create_installer_windows.sh && mkdir /cygdrive/c/installer && cp windows_installer/*exe /cygdrive/c/installer/"

      - name: Create smoke test kit
        shell: cmd
        run: C:\cygwin_coq_platform\bin\bash --login -c "cd /platform/ && shell_scripts/create_smoke_test_kit.sh && mkdir /cygdrive/c/smoke && cp -ra smoke-test-kit/* /cygdrive/c/smoke/"

      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v4
        with:
          name: 'Windows installer ${{matrix.variant}} ${{matrix.architecture}}'
          path: C:\installer\*.exe
          retention-days: 5

      - name: 'Upload smoke test kit'
        uses: actions/upload-artifact@v4
        with:
          name: 'Smoke Test Kit Windows ${{matrix.variant}} ${{matrix.architecture}}'
          path: C:\smoke\
          retention-days: 5

  Windows_smoke:
    name: Smoke test Windows
    needs: Windows_platform
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        architecture:
          - '64'
        variant:
          - '9.0+preview~2025.08'
          - '8.20~2025.01'

    steps:
      - name: 'Download Artifact'
        uses: actions/download-artifact@v4
        id: download
        with:
          name: 'Windows installer ${{matrix.variant}} ${{matrix.architecture}}'

      - name: 'Download smoke test kit'
        uses: actions/download-artifact@v4
        id: download-smoke
        with:
          name: 'Smoke Test Kit Windows ${{matrix.variant}} ${{matrix.architecture}}'

      - name: 'Run Installer'
        shell: cmd
        run: |
          cd ${{steps.download.outputs.download-path}}
          FOR %%f IN (*.exe) DO %%f /S /D=C:\Coq

      - name: 'Smoke coqc'
        shell: cmd
        run: C:\Coq\bin\coqc.exe -v

      - name: 'Run Windows smoke test kit'
        shell: cmd
        run: |
          CD ${{steps.download-smoke.outputs.download-path}}
          DIR
          SET PATH=C:\Coq\bin\;%PATH%
          CALL run-smoke-test.bat
